export { toCumulativeCases } from "./toCumulativeCases";
export { toActiveCases } from "./toActiveCases";
export { toNewCases } from "./toNewCases";
export { toObservations } from "./toObservations";
export { toDailyObservations } from "./toDailyObservations";
export { toConfirmedPercentage } from "./toConfirmedPercentage";
export { toCaseFatalityRate } from "./toCaseFatalityRate";
export { toCFR1 } from "./toCFR1";
export { toCFR2 } from "./toCFR2";